# Generated by Django 4.0.4 on 2022-06-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_last_updated_product_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['unit_price', 'title']},
        ),
    ]
